### PR TITLE
[MM-340] Fix issue of receiving incorrect notification for various events in DM

### LINKED ISSUE #469: Add feature to receive notification when user is removed as the assignee or the reviewer

### PR DESCRIPTION
**Pull request by ayusht2810**
#### Summary
- Fixed issue of receiving incorrect notifications for various events in the DM
- Added logic to get notification when user is added as assignee or reviewer

#### Ticket Link
- Fixes #469 

### Checklist
- [x] Completed dev testing
- [x] `make test` Ran test cases and ensured they are passing
- [x] `make check-style` Ran style check and ensured both webapp and server pass the checks

#### What to test?
- Check for the notification when MR is assigned to you as a reviewer or assignee

### CODE REVIEW

File: server/webhook/merge_request.go [hunk 1]
```diff
@@ -148,3 +231,72 @@ func (w *webhook) handleChannelMergeRequest(ctx context.Context, event *gitlab.M
 
 	return res, nil
 }
+
+func (w *webhook) handleDMNotificationUsers(authorID int, previousUsers, currentUsers []*gitlab.EventUser) (bool, []string, []string) {
```
Comment (mickmister) [inline server/webhook/merge_request.go:235]:
```suggestion
func (w *webhook) calculateUserDiffs(authorID int, previousUsers, currentUsers []*gitlab.EventUser) (bool, []string, []string) {
```

File: server/webhook/merge_request.go [hunk 2]
```diff
@@ -29,57 +29,140 @@ func (w *webhook) handleDMMergeRequest(event *gitlab.MergeEvent) ([]*HandleWebho
...
 			}
 
-			message = fmt.Sprintf("[%s](%s) assigned you to merge request [%s!%v](%s)", senderGitlabUsername, w.gitlabRetreiver.GetUserURL(senderGitlabUsername), event.ObjectAttributes.Target.PathWithNamespace, event.ObjectAttributes.IID, event.ObjectAttributes.URL)
+			// Handle change in reviewers
+			if event.Changes.Reviewers.Current != nil || event.Changes.Reviewers.Previous != nil {
+				isAuthorPresent, updatedPreviousUsers, updatedCurrentUsers := w.handleDMNotificationUsers(event.ObjectAttributes.AuthorID, event.Changes.Reviewers.Previous, event.Changes.Reviewers.Current)
+
+				// Check if the MR author is present in the assignee changes
+				if !isAuthorPresent {
+					message = fmt.Sprintf("[%s](%s) updated the list of reviewers for the merge request [%s!%v](%s)", senderGitlabUsername, w.gitlabRetreiver.GetUserURL(senderGitlabUsername), event.ObjectAttributes.Target.PathWithNamespace, event.ObjectAttributes.IID, event.ObjectAttributes.URL)
```
Comment (mickmister) [inline server/webhook/merge_request.go:95]: I'm not sure if this is something I would want to get a notification for. Mainly just "assigned you" or "requested your review" like the GitHub plugin works @hanzei What do you think?

File: server/webhook/merge_request.go [hunk 3]
```diff
@@ -29,57 +29,140 @@ func (w *webhook) handleDMMergeRequest(event *gitlab.MergeEvent) ([]*HandleWebho
...
+			}
+
+			// Check if multiple events happened in single webhook event
+			if w.checkForMultipleEvents(event) {
+				message = fmt.Sprintf("[%s](%s) updated the merge request [%s!%v](%s)", senderGitlabUsername, w.gitlabRetreiver.GetUserURL(senderGitlabUsername), event.ObjectAttributes.Target.PathWithNamespace, event.ObjectAttributes.IID, event.ObjectAttributes.URL)
+				handlers = []*HandleWebhook{{
+					Message: message,
+					ToUsers: toUsers,
+					From:    senderGitlabUsername,
+				}}
```
Comment (mickmister) [inline server/webhook/merge_request.go:129]: Should we append here instead of reassigning `handlers` to an array with one element? I would still want to receive the notification for being assigned to an issue/MR

File: server/webhook/merge_request.go [hunk 4]
```diff
@@ -29,57 +29,140 @@ func (w *webhook) handleDMMergeRequest(event *gitlab.MergeEvent) ([]*HandleWebho
...
+					message = fmt.Sprintf("[%s](%s) updated the list of reviewers for the merge request [%s!%v](%s)", senderGitlabUsername, w.gitlabRetreiver.GetUserURL(senderGitlabUsername), event.ObjectAttributes.Target.PathWithNamespace, event.ObjectAttributes.IID, event.ObjectAttributes.URL)
+					handlers = append(handlers, &HandleWebhook{
+						Message: message,
+						ToUsers: []string{authorGitlabUsername},
+						From:    senderGitlabUsername,
+					})
+				}
+
+				if len(updatedPreviousUsers) != 0 {
+					message = fmt.Sprintf("[%s](%s) removed you as a reviewer from the merge request [%s!%v](%s)", senderGitlabUsername, w.gitlabRetreiver.GetUserURL(senderGitlabUsername), event.ObjectAttributes.Target.PathWithNamespace, event.ObjectAttributes.IID, event.ObjectAttributes.URL)
```
Comment (mickmister) [inline server/webhook/merge_request.go:104]: 0/5 on if the user would want to be notified for this. I can see the value here

File: server/webhook/merge_request.go (hunk 3 above)
Comment (ayusht2810) [reply server/webhook/merge_request.go:129]: We have not appended here as there are multiple events. If we just append it to the array, then there will be multiple posts on the mattermost channel for the single event. Shouldn't we just post a single time for an event? Please let me know your opinions on this.

**Comment by ayusht2810** [comment]
@mickmister updated the function name. Other comments are pending on @hanzei and your reply.

File: server/webhook/merge_request.go (hunk 2 above)
Comment (hanzei) [reply server/webhook/merge_request.go:95]: Sounds good :+1:

File: server/webhook/merge_request.go (hunk 4 above)
Comment (hanzei) [reply server/webhook/merge_request.go:104]: Yeah, I think we don't need a notification for that case.

File: server/webhook/merge_request.go [hunk 5]
```diff
@@ -148,3 +231,72 @@ func (w *webhook) handleChannelMergeRequest(ctx context.Context, event *gitlab.M
 
 	return res, nil
 }
+
+func (w *webhook) calculateUserDiffs(authorID int, previousUsers, currentUsers []*gitlab.EventUser) (bool, []string, []string) {
```
Comment (hanzei) [inline server/webhook/merge_request.go:235]: That method could need a comment explaining what it does.

File: server/webhook/merge_request.go [hunk 6]
```diff
@@ -148,3 +231,72 @@ func (w *webhook) handleChannelMergeRequest(ctx context.Context, event *gitlab.M
...
+		}
+	}
+
+	return isAuthorPresent, updatedPreviousUsers, updatedCurrentUsers
+}
+
+func (w *webhook) checkForMultipleEvents(event *gitlab.MergeEvent) bool {
+	eventCount := 0
+	if event.Changes.Labels.Current != nil || event.Changes.Labels.Previous != nil {
+		eventCount++
```
Comment (hanzei) [inline server/webhook/merge_request.go:270]: Can the code simply return with `return true` in this case?

Comment (ayusht2810) [reply server/webhook/merge_request.go]: Removed the above function in the updated logic as there was no need for it.

**Comment by ayusht2810** [comment]
@hanzei Fixed the review fixes. Please re-review.

File: server/webhook/merge_request.go [hunk 7]
```diff
@@ -148,3 +182,20 @@ func (w *webhook) handleChannelMergeRequest(ctx context.Context, event *gitlab.M
 
 	return res, nil
 }
+
+// calculateUserDiffs function takes previousUsers and currentUsers of an event, finds the change in the user list, and returns the updated current user list.
```
Comment (hanzei) [inline server/webhook/merge_request.go:186]: Nit: break into multiple lines

**Review by hanzei — APPROVED** [review]
LGTM

File: server/webhook/merge_request.go (hunk 7 above)
Comment (mickmister) [reply server/webhook/merge_request.go]: @ayusht2810 Go comments above functions are typically done with `//` like

```go
// calculateUserDiffs function takes previousUsers and currentUsers of an event,
// finds the change in the user list, and returns the updated current user list.
```

**Review by mickmister — APPROVED** [review]

File: server/webhook/merge_request.go [hunk 8]
```diff
@@ -148,3 +182,23 @@ func (w *webhook) handleChannelMergeRequest(ctx context.Context, event *gitlab.M
 
 	return res, nil
 }
+
+/*
+calculateUserDiffs function takes previousUsers and currentUsers of an event,
+finds the change in the user list, and returns the updated current user list.
+*/
```
Comment (hanzei) [inline server/webhook/merge_request.go:189]:
```suggestion
// calculateUserDiffs takes previousUsers and currentUsers of an event,
finds the change in the user list, and returns the updated current user list.
```

**Review by AayushChaudhary0001 — APPROVED** [review]
The above PR has been tested for the following scenarios:

- Tested the notification when MR is assigned to you as a reviewer or assignee
- Tested the notification when MR is assigned to other user as a reviewer or assignee

The PR was working fine for both the conditions, LGTM. Approved
