### PR TITLE
[GH-383] Fix UX for member_access_request in right hand sidebar

### LINKED ISSUE #383: UX gap when group membership is requested
An issue is being addresses for group membership requests https://github.com/mattermost/mattermost-plugin-gitlab/pull/378

But there were also a couple UX gaps identified.

1. There does not seem to be a message body implemented for the RHS content here.
image

2. The shorthand in the ToDo list is missing the name of the requester
image

### PR DESCRIPTION
**Pull request by raghavaggarwal2308**
#### Summary
- Fixed the UI for the "member_access_request" type todo/unread in RHS
- A PR #404 is already open to fix the UX gap for todos posted after running the `/gitlab todo` command.

#### Screenshots
image

#### What to test?
- ToDos of type "member_access_request" are rendered properly in the RHS.

###### Steps to reproduce:
1. Connect your Gitlab account.
2. Generate a notification of type "member_access_request" on the Gitlab side. (You can do so by making an access request to one of your project/group by some another user)
3. Open the RHS for todos/unreads.

###### Environment:
MM version: v7.8.2
Node version: 14.18.0
Go version: 1.19.0

#### Ticket Link
Fixes #383

### CODE REVIEW

File: webapp/src/components/sidebar_right/gitlab_items.tsx [hunk 1]
```diff
@@ -174,17 +176,14 @@ function GitlabItems({item, theme}: GitlabItemsProps) {
...
                 {number}
-                <span className='light'>{repoName}</span>
+                {repoName && <span className='light'>({repoName})</span>}
             </div>
             {labels}
             <div
                 className='light'
                 style={style.subtitle}
             >
-                {'Opened'}
```
Comment (mickmister) [inline webapp/src/components/sidebar_right/gitlab_items.tsx:184]: Do we want this to be here in some cases still?

File: webapp/src/components/sidebar_right/gitlab_items.tsx [hunk 2]
```diff
@@ -194,7 +193,7 @@ function GitlabItems({item, theme}: GitlabItemsProps) {
                 {item.action_name && (
                     <>
                         <div>{item.updated_at && `Updated ${formatTimeSince(item.updated_at)} ago.`}</div>
-                        {notificationReasons[item.action_name]}
+                        {item.action_name == ACTION_NAME_MEMBER_ACCESS_REQUESTED && <a href={item.author.web_url}>{item.author.name}</a>} {notificationReasons[item.action_name]}
```
Comment (mickmister) [inline webapp/src/components/sidebar_right/gitlab_items.tsx:196]: I think this may be easier to read like this:

```js
const includeNotificationAuthor = item.action_name == ACTION_NAME_MEMBER_ACCESS_REQUESTED; 
```

```suggestion
        {includeNotificationAuthor && <a href={item.author.web_url}>{item.author.name}</a>} 
        {notificationReasons[item.action_name]}
```

Notice the separate lines as well

**Comment by raghavaggarwal2308** [comment]
@mickmister Fixed the review comments mentioned by you

**Review by mickmister — APPROVED** [review]

**Review by AayushChaudhary0001 — APPROVED** [review]
Tested and approved. LGTM
